all:
  children:
    servers:
      hosts:
        raspi:
          ansible_host: 192.168.1.20
          ansible_python_interpreter: /usr/bin/python3
        albedo:
          ansible_host: 192.168.1.10
          ansible_python_interpreter: /usr/bin/python3