---
# tasks hostname file for basic

# Change le Hostname
- name: Change the hostname to our standard
  hostname:
    name: '{{ hostname_short }}.{{ hostname_domain }}'

# Ajoute le new hostname & delete le old hostname dans /etc/hosts
- name: Fix /etc/hosts removing the old hostname
  lineinfile:
    state: present
    dest: /etc/hosts
    regexp: '^{{ ansible_default_ipv4.address }}'
    line: '{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}'

# Relance la machine
- name: restart machine
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: True
  when: reboot is defined

# Attend que la machine revienne
- name: Waiting for server to come back up
    local_action: 'wait_for host="{{ inventory_hostname }}" state=started'