---
# tasks hostname file for basic

# Change le Hostname
- name: Change the hostname to our standard
  hostname:
    name: '{{ hostname }}'

# Ajoute le new hostname & delete le old hostname dans /etc/hosts.old
- name: Fix /etc/hosts.old removing the old hostname
  lineinfile:
    state: present
    dest: /etc/hosts.old
    regexp: '^{{ ansible_default_ipv4.address }}'
    line: '{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}'

## Relance la machine
- name: Reboot a machine
  reboot:
    reboot_timeout: 3600