---
# tasks tools for CentOS file for basic

#Cette tache update les repos de yum
- name: Install yum utils
  yum:
    name: yum-utils
    state: latest

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

# Installe les paquets de bases for
- name: Install Tools basics for CentOS
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages: "{{ rpms }}"
